# Generated by Django 5.1.6 on 2025-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.CharField(max_length=255, verbose_name='Контроллер')),
                ('status', models.CharField(choices=[('DON', 'сделано'), ('WRK', 'в работе'), ('CNS', 'отменено'), ('WAT', 'ожидает')], max_length=3, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'срочно'), (2, 'средней срочности'), (3, 'не срочно'), (4, 'отложено')], default=3, verbose_name='Приоритет')),
                ('remark_datetime', models.DateField(verbose_name='Дата замечания')),
                ('remark', models.CharField(max_length=255, verbose_name='Замечание')),
                ('shift_task', models.IntegerField(verbose_name='Номер задания')),
            ],
        ),
    ]
